field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  0ce9bef7-d2ea-4e7e-8ead-86e6d8771e8d:
    tabs:
      -
        elements:
          -
            fieldUid: ad542dfc-2d07-4de2-9875-c811ffc1be61 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d52452b5-af79-4664-a8e4-5d9ce4cc63ea # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 051d92e2-649b-4487-b9de-31b3c4bb7d86 # Audio Datei
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  051d92e2-649b-4487-b9de-31b3c4bb7d86: # Audio Datei
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audioFile
    instructions: 'Unterstützte Formate: mp3, ogg, wav. Der Upload einer umfangreichen Audio-Datei benötigt etwas Zeit. Bitte Geduld, bis der Spinner rechts oben im Upload-Fenster verschwindet.'
    name: 'Audio Datei'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: audio
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ad542dfc-2d07-4de2-9875-c811ffc1be61: # Title
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: 100
      charLimit: null
      code: ''
      columnType: string
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d52452b5-af79-4664-a8e4-5d9ce4cc63ea: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: audio
name: Audio
sortOrder: 6
