field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  0ce9bef7-d2ea-4e7e-8ead-86e6d8771e8d:
    tabs:
      -
        elements:
          -
            fieldUid: 051d92e2-649b-4487-b9de-31b3c4bb7d86 # Audio File
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  051d92e2-649b-4487-b9de-31b3c4bb7d86: # Audio File
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: audioFile
    instructions: 'Unterstützte Formate: mp3, ogg, wav. Der Upload einer umfangreichen Audio-Datei benötigt etwas Zeit. Bitte Geduld, bis der Spinner rechts oben im Upload-Fenster verschwindet.'
    name: 'Audio File'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds:
        - audio
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: audio
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Select file'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: audio
name: Audio
sortOrder: 7
