field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  944975d0-4058-43ea-85dd-7342540932e6:
    tabs:
      -
        elements:
          -
            fieldUid: 6c68905c-e96f-42e0-bc08-1f1f9d58d19f # Asset
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6c68905c-e96f-42e0-bc08-1f1f9d58d19f: # Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: asset
    instructions: ''
    name: Asset
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: false
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:49ccb4b8-c82b-4daf-9af9-1af874ad6dd4' # Embeds
      defaultUploadLocationSubpath: embeds
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Embed auswählen'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      singleUploadLocationSubpath: '{owner.site.handle}'
      source: null
      sources:
        - 'volume:49ccb4b8-c82b-4daf-9af9-1af874ad6dd4' # Embeds
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: embed
name: Embed
sortOrder: 9
