field: 266ac6c3-03c0-40eb-8f24-c5c22ed1c5c0 # Content
fieldLayouts:
  ed608b4f-1636-46c5-8d82-71c445926709:
    tabs:
      -
        elements:
          -
            fieldUid: 512edbee-e5b1-4422-9597-eeffd72ee9e5 # __blank__
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5cc78695-cf9e-4492-af63-2f65b4b8c1aa # Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5cc78695-cf9e-4492-af63-2f65b4b8c1aa: # Display
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: display
    instructions: ''
    name: Display
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Accordion
            -
              - value
              - accordion
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  512edbee-e5b1-4422-9597-eeffd72ee9e5: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: items
    instructions: ''
    name: __blank__
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - e35ec4e7-302c-49f6-b5ae-a95120fbd4c0 # Question
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 8fb04690-63b2-4e65-bb13-def05a978110 # Answer
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_34_items}}'
      fieldLayout: row
      maxRows: ''
      minRows: '1'
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add question/answer'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: faq
name: FAQ
sortOrder: 13
