field: e62d63b0-c299-42ce-aeef-86a69f7e676c # Seo Fields
fieldLayouts:
  a3a223e7-de48-4b77-9d19-7fd60f6e0131:
    tabs:
      -
        elements:
          -
            fieldUid: b0cfc7f4-d446-41bb-87ab-dc16b1481540 # Alternative Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c7e95a7-7a87-46ad-974e-8ce3846ef68b # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 34581043-4880-49b9-b16a-cba691fa21f3 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 90724a6b-55ad-446f-be50-7aea7e1fb067 # Robots
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9c7e95a7-7a87-46ad-974e-8ce3846ef68b: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  90724a6b-55ad-446f-be50-7aea7e1fb067: # Robots
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: robots
    instructions: ''
    name: Robots
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - all
            -
              - value
              - all
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - noindex
            -
              - value
              - noindex
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - nofollow
            -
              - value
              - nofollow
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  34581043-4880-49b9-b16a-cba691fa21f3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      defaultUploadLocationSubpath: seo
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Select image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:f2bd38f3-47f5-4e49-be18-fa89073255fd' # Media
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b0cfc7f4-d446-41bb-87ab-dc16b1481540: # Alternative Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: alternativeTitle
    instructions: ''
    name: 'Alternative Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: settings
name: Settings
sortOrder: 1
