fieldLayouts:
  60760598-141f-44c5-84ac-cd02852ff8aa:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            template: _special/dumpelementsnapsho
            type: craft\fieldlayoutelements\Template
            width: 100
          -
            fieldUid: ca83549a-9120-4edc-879c-5d1f843cd4a2 # Snapshot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhalt
        sortOrder: 1
handle: default
hasTitleField: true
name: Standard
section: 1e572ace-db73-446d-bc4f-0c5cae3d58e7 # Contact Message
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
