tabs:
  -
    elements:
      -
        fieldUid: f6ff43e3-8e77-457f-91cb-101f517889c9 # Teaser
        instructions: ''
        label: Kurzbeschreibung
        required: ''
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: b683b318-aee5-4bb2-a3a4-40fc6cf445cc # Phone
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: Content
    sortOrder: 1
