columnSuffix: vutiojub
contentColumnType: string(240)
fieldGroup: 609778c1-e7ba-47fc-bd62-7f2c99f0f0ee # Assets
handle: altText
instructions: ''
name: 'Alt Text'
searchable: true
settings:
  byteLimit: null
  charLimit: 60
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
