columnSuffix: null
contentColumnType: string
fieldGroup: d868de82-ae37-4897-a6bb-ef08e919650b # Common
handle: copyright
instructions: ''
name: Copyright
searchable: true
settings:
  byteLimit: null
  charLimit: 50
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
