columnSuffix: null
contentColumnType: string
fieldGroup: bb94c9b2-f8e4-4729-97b4-9367ffd54772 # Person
handle: eMail
instructions: ''
name: E-Mail
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
