columnSuffix: null
contentColumnType: string
fieldGroup: 6f31e23d-56c9-4afe-aacf-25ec0d12b2c2 # Guide
handle: guideContent
instructions: 'Wenn leer, muss eine twig/md-Datei mit dem Namen des slugs existieren, die dann angezeigt wird.'
name: 'Guide Inhalt'
searchable: false
settings:
  contentTable: '{{%matrixcontent_guidecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: none
type: craft\fields\Matrix
