columnSuffix: null
contentColumnType: string
fieldGroup: 6f31e23d-56c9-4afe-aacf-25ec0d12b2c2 # Guide
handle: includeGuides
instructions: ''
name: 'Include Guides'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:61350169-3950-4815-aea9-b171958d6d8a' # Guide
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
