columnSuffix: ljsesmqn
contentColumnType: string
fieldGroup: d868de82-ae37-4897-a6bb-ef08e919650b # Common
handle: intro
instructions: ''
name: Intro
searchable: true
settings:
  byteLimit: 255
  charLimit: null
  code: ''
  columnType: string
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
