columnSuffix: nlkxovzt
contentColumnType: string(120)
fieldGroup: f15bff68-e0e6-422d-a615-9e22d733e1f0 # Global
handle: siteName
instructions: ''
name: 'Site Name'
searchable: false
settings:
  byteLimit: null
  charLimit: 30
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
