columnSuffix: ngzdzryf
contentColumnType: text
fieldGroup: d868de82-ae37-4897-a6bb-ef08e919650b # Common
handle: snapshot
instructions: ''
name: Snapshot
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
