field: 512edbee-e5b1-4422-9597-eeffd72ee9e5 # __blank__
fieldLayouts:
  93371f62-9ff6-4700-9462-571076c33835:
    tabs:
      -
        elements:
          -
            fieldUid: e35ec4e7-302c-49f6-b5ae-a95120fbd4c0 # Question
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8fb04690-63b2-4e65-bb13-def05a978110 # Answer
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8fb04690-63b2-4e65-bb13-def05a978110: # Answer
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: answer
    instructions: ''
    name: Answer
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e35ec4e7-302c-49f6-b5ae-a95120fbd4c0: # Question
    columnSuffix: null
    contentColumnType: string(240)
    fieldGroup: null
    handle: question
    instructions: ''
    name: Question
    searchable: true
    settings:
      byteLimit: null
      charLimit: 60
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
