defaultPlacement: end
enableVersioning: true
handle: contactMessage
name: 'Contact Message'
propagationMethod: all
siteSettings:
  6cae2408-4e31-46df-8a5b-33f31d339176: # Deutsch
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
